### ISSUE TITLE
The provided mnemonic does not respect the BIP39 standard

### ISSUE THREAD

**Issue by vevenet** [ASeriousMister/seedbf#2]
HI , I try to use another works like :theocratic malformations eberhard weightings  
i git this ugly message : The provided mnemonic does not respect the BIP39 standard
after i get the b39en from  SeedCheck and save and use worgs like :  salon ten wear  lounge
seedbf.py  -p passphraselist.txt -s 'salon ten wear  lounge' also get again a ugly message : 
Passphrase accident not used with standard BIP44, BIP49 and BIP84 derivation path←

can u help me to understand why ?

**Comment by ASeriousMister** [comment]
Hello. Before starting to check the passphrases, the tool checks if the provided words respect the BIP39 standard using the hdwallet python library. In the examples you provided, seeds seem to be incorrect. They should be 9, 12, 15, 18, 21 or 24 words long and the last word has to fulfill the checksum requirements. If the provided seed is correct, the verifies if it has been used for a Bitcoin wallet after being extended with one of the passphrases in the provided txt list. Try the tool with a valid BIP39 seed, maybe generate one with Ian Coleman's BIP39 tool for test purposes. Let me know if you encounter other issues.
PS: the tool has been testes in Linux. I do not know if it works correctly with Windows.

**Comment by vevenet** [comment]
I make a new btc address , and i try search with this words : 'imitate minute bulk rapid eager captain case envelope submit bike birth unfold'

`C:\Users\asus\Desktop\seedbf-main\seedbf-main> python seedbf.py -p b39en -s 'imitate minute bulk rapid eager captain
case envelope submit bike birth unfold'
←[92mMnemonic seed accepted!←[0m
←[91mProvided passphrase list not found! Please specify full path to the file←[0m
PS C:\Users\asus\Desktop\seedbf-main\seedbf-main> python seedbf.py -p b39en.txt -s 'imitate minute bulk rapid eager capt
ain case envelope submit bike birth unfold'
←[92mMnemonic seed accepted!←[0m
←[93m- - - - - - - - - -
Checking 2048 passphrases...
←[0m
←[36mHow many addresses do you want to check for each derivation path?
←[0m2
['1B71E1UUeqc3mPNPhVAzApQurLWVjSh9Rs', '35AkaH9R1J6QdLFWY1VwyrVCXxi3sG8noa', 'bc1qf5jhls09wn78z2mxmfjrr5vk98sunzu7fn3ges
', '1Q61xdB9joAG8b3g8g3R6t8iXbUshV17cK', '3QxZUNAddJbQa1TSfitMcucz1AxEVRV7Zj', 'bc1q4hqlnavw3jczztrwun2rtsj5892hgudua08f
kc']
←[95mPassphrase abandon not used with standard BIP44, BIP49 and BIP84 derivation path←[0m
['16oEVeAE6QpSuGAEGnt43TL8mePBoJzW1v', '3CfJp9Nb5wnWjTkeNiTfSqrXVseZ4xwij9', 'bc1q0lkku8n9gap7levvgjl7fe0n4vg83psex4rjz6
', '13Wvjf7ds6ib9z4BukTnf3S6ngV1yvVFi4', '36gvWooRCVt7bQtHJNNfg6U4AL1uiNf3wi', 'bc1q4ly5vm2r5jvlx2hqv9tszvpyms7a6emp53q3
6v']
←[95mPassphrase ability not used with standard BIP44, BIP49 and BIP84 derivation path←[0m
['1JSHeDc1s7G9JkHS2Bo2r2pEK7NuEyHZdi', '3MoSeQb1VY4rUUKL5diJ2ajAiR7hqwoAsu', 'bc1qqsqg356tyk89mar6cknqvkeksyjtc5q7dmjx3p
', '1JRGmpD6EGYXgpwKdNJZ9o7vHU3876jnh5', '3GBeECAELdGAcjpYwgKiajsmAYvzAvV7bg', 'bc1q5h2r2w77m7cdyl9gx0ar9z2xuvy8c8f2sh4k
x2']
←[95mPassphrase able not used with standard BIP44, BIP49 and BIP84 derivation path←[0m
['13VCytGcPHrqNqqHgbT1wP87D4A25uga1U', '3BaMWpVnnsm7Sm6unLtKj392PeLVDdtWbn', 'bc1qr5y9ngc708qtzq3cy098hzzwyn0fpe62s95hz2
', '1HDnu4x4hVLrV4mxDj2PEDP61ccxBc3DVm', '3KSeDu83kKYaK19KmpZSSetZmB9wQUXCyC', 'bc1qu0xg0xg0xlxaenkxgeqsa8z9wueffj4kt5e6
sl']
←[95mPassphrase about not used with standard BIP44, BIP49 and BIP84 derivation path←[0m










`

**Comment by ASeriousMister** [comment]
Now it seems to work properly. If you have other questions do not hesitate to contact me :)
